# Generated by Django 4.2.1 on 2023-05-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='email',
        ),
        migrations.RemoveField(
            model_name='auth',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='auth',
            name='last_name',
        ),
        migrations.AddField(
            model_name='worker',
            name='Gov_id_type',
            field=models.CharField(default='Aadhar', max_length=100),
        ),
        migrations.AddField(
            model_name='worker',
            name='Salary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='Gov_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
