# Generated by Django 4.2.1 on 2023-05-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_auth_email_remove_auth_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='Education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='Salary_type',
            field=models.CharField(choices=[('D_B', 'Daily Basis'), ('H_B', 'Hour Basis')], max_length=100),
        ),
    ]
