# Generated by Django 4.2.1 on 2023-05-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_worker_education_alter_worker_salary_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='Profile_pic',
        ),
        migrations.AddField(
            model_name='worker',
            name='Profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
